from pathlib import Path

import numpy as np
import pandas as pd
import plotly.express as px
import streamlit as st

# Pre-generated by fetch_data.py (yfinance, offline). The app reads this CSV —
# no network/API dependency at runtime. Re-run fetch_data.py to refresh.
DATA_FILE = Path(__file__).parent / "stocks.csv"

# --- Theme constants: one green, one red, used everywhere for gains/losses ---
GREEN = "#16a34a"
RED = "#dc2626"
GREY = "#9ca3af"
PLOTLY_TEMPLATE = "plotly_white"

st.set_page_config(
    page_title="Equity Performance Dashboard",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# No sidebar is used — hide it (and its expand arrow) entirely for a clean full-width layout.
st.markdown(
    "<style>[data-testid='stSidebar'], [data-testid='stSidebarCollapsedControl'] {display: none;}</style>",
    unsafe_allow_html=True,
)

st.title("Equity Performance Dashboard")
st.caption("Prices indexed to 1.00 on the first trading day — every figure shows growth since January 2018.")

# Hardcoded at build time (source: Apple Newsroom, Q3 FY2024 results) — not fetched at runtime.
st.info(
    "Did you know? Apple set June-quarter records in Q3 FY2024 with $85.8B in revenue "
    "(up 5% YoY) and an all-time-high in Services revenue."
)


@st.cache_data
def load_data():
    # Read the locally generated CSV (date + one column per ticker, indexed to 1.00).
    df = pd.read_csv(DATA_FILE)
    df["date"] = pd.to_datetime(df["date"])
    return df


def max_drawdown(series):
    """Worst peak-to-trough drop over the period, as a negative fraction."""
    running_peak = series.cummax()
    drawdown = series / running_peak - 1.0
    return drawdown.min()


def cagr(series, dates):
    """Compound annual growth rate as a fraction."""
    years = (dates.iloc[-1] - dates.iloc[0]).days / 365.25
    total_return = series.iloc[-1] / series.iloc[0]
    return total_return ** (1 / years) - 1


def daily_volatility(series):
    """Standard deviation of daily returns, as a fraction."""
    return series.pct_change().std()


def chunk(items, size):
    """Yield successive slices so metric cards wrap instead of getting cramped."""
    for i in range(0, len(items), size):
        yield items[i : i + size]


df = load_data()
tickers = [c for c in df.columns if c != "date"]

# Inline stock picker at the top of the page — pill-style multi-select.
chosen = st.pills(
    "Compare stocks",
    tickers,
    selection_mode="multi",
    default=["AAPL", "MSFT", "GOOG"],
)
if not chosen:
    st.warning("Select at least one stock above.")
    st.stop()

# --- Per-stock stats, computed once over the full period ---
stats = {}
for t in chosen:
    stats[t] = {
        "growth": (df[t].iloc[-1] - 1) * 100,            # total growth %
        "cagr": cagr(df[t], df["date"]) * 100,           # annualized %
        "vol": daily_volatility(df[t]) * 100,            # daily std %
        "drawdown": max_drawdown(df[t]) * 100,           # worst dip %
        "multiple": df[t].iloc[-1],                      # ending multiple
    }

# ============================ OVERVIEW ============================
st.subheader("Overview")
best = max(stats, key=lambda t: stats[t]["growth"])
with st.container(border=True):
    c1, c2 = st.columns([1, 2])
    c1.metric("Best performer", best, f"{stats[best]['growth']:+.1f}%")
    c2.metric(
        f"{best} ending value",
        f"{stats[best]['multiple']:.2f}×",
        f"CAGR {stats[best]['cagr']:+.1f}%",
    )

# ====================== PER-STOCK SNAPSHOT =======================
st.subheader("By stock")
# Wrap cards in rows of up to 3 so they stay readable on smaller screens.
for row in chunk(chosen, 3):
    cols = st.columns(len(row))
    for col, t in zip(cols, row):
        with col.container(border=True):
            st.markdown(f"**{t}**")
            st.metric("Total growth", f"{stats[t]['multiple']:.2f}×", f"{stats[t]['growth']:+.1f}%")
            # Drawdown is always a loss → show it in red via a negative delta.
            st.metric("Max drawdown", f"{stats[t]['drawdown']:.1f}%", f"{stats[t]['drawdown']:.1f}%")

# ============================= CHARTS ============================
st.subheader("Charts")
min_date = df["date"].min().to_pydatetime()
max_date = df["date"].max().to_pydatetime()
start, end = st.slider(
    "Zoom the price chart to a date range",
    min_value=min_date,
    max_value=max_date,
    value=(min_date, max_date),
    format="YYYY-MM-DD",
)

line_tab, bar_tab = st.tabs(["Price over time", "Total growth"])

with line_tab:
    view = df[(df["date"] >= start) & (df["date"] <= end)]
    fig_line = px.line(view, x="date", y=chosen, template=PLOTLY_TEMPLATE)
    fig_line.update_layout(
        margin=dict(l=0, r=0, t=10, b=0),
        legend_title_text="",
        yaxis_title="Indexed price",
        xaxis_title="",
    )
    st.plotly_chart(fig_line, use_container_width=True)

with bar_tab:
    bar_df = pd.DataFrame(
        {"Stock": chosen, "Growth %": [stats[t]["growth"] for t in chosen]}
    )
    bar_df["Result"] = np.where(bar_df["Growth %"] >= 0, "Gain", "Loss")
    fig_bar = px.bar(
        bar_df,
        x="Stock",
        y="Growth %",
        color="Result",
        color_discrete_map={"Gain": GREEN, "Loss": RED},
        template=PLOTLY_TEMPLATE,
    )
    fig_bar.update_layout(margin=dict(l=0, r=0, t=10, b=0), legend_title_text="")
    st.plotly_chart(fig_bar, use_container_width=True)

# ========================= COMPARISON TABLE =====================
st.subheader("Comparison")
table = pd.DataFrame(
    {
        "Total Growth %": [stats[t]["growth"] for t in chosen],
        "CAGR %": [stats[t]["cagr"] for t in chosen],
        "Volatility %": [stats[t]["vol"] for t in chosen],
        "Max Drawdown %": [stats[t]["drawdown"] for t in chosen],
    },
    index=pd.Index(chosen, name="Stock"),
)


def color_by_sign(v):
    return f"color: {GREEN if v >= 0 else RED}; font-weight: 600;"


styled = (
    table.style.format(
        {
            "Total Growth %": "{:+.1f}%",
            "CAGR %": "{:+.1f}%",
            "Volatility %": "{:.2f}%",
            "Max Drawdown %": "{:.1f}%",
        }
    )
    .map(color_by_sign, subset=["Total Growth %", "CAGR %"])
    .map(lambda v: f"color: {RED}; font-weight: 600;", subset=["Max Drawdown %"])
    .map(lambda v: f"color: {GREY};", subset=["Volatility %"])
)
st.dataframe(styled, use_container_width=True)
st.caption(
    "CAGR = annualized return. Volatility = std dev of daily returns. "
    "Max drawdown = worst peak-to-trough drop over the full period."
)

# ====================== INVESTMENT CALCULATOR ===================
st.subheader("What if I invested?")
with st.container(border=True):
    calc_col1, calc_col2 = st.columns(2)
    pick = calc_col1.selectbox("Stock", chosen)
    amount = calc_col2.number_input(
        "Starting amount ($)", min_value=1.0, value=1000.0, step=100.0
    )

    final_value = amount * df[pick].iloc[-1]
    profit = final_value - amount
    st.metric(
        f"{pick} — value at end of period",
        f"${final_value:,.2f}",
        f"${profit:,.2f} ({stats[pick]['growth']:+.1f}%)",
    )
    st.caption("Assumes a one-time investment on the first day, held through the end of the period.")
